### PR TITLE
Fix/range check

### LINKED ISSUE #168: bug: integer overflow when attempting to run fibonacci program
When attempting to run the fibonacci program (see https://github.com/keep-starknet-strange/cairo-zig/pull/157), we are currently seeing an integer overflow panic.

```
thread 4036341 panic: integer overflow
/Users/jmsb/exps/internet-computers/starknet/cairo-zig/src/vm/core.zig:284:41: 0x1003d51d3 in runInstruction (cairo-zig)
        const off_1 = instruction.off_1 + (@as(i16, 1) << (OFFSET_BITS - 1));
```

Seeing as the context for this code as it was written in the cairo vm in rust as a performance optimization (see [inciting pr](https://github.com/lambdaclass/cairo-vm/pull/1080/files#diff-b921c7e31d9a240fb50b65ba95da0bc8a2565a2194e23e6ca231e8a1afc0ddafR401), perhaps we can remove for now and revisit for a performance based milestone later.

### LINKED ISSUE #178: test: add test coverage for `RangeCheckBuiltinRunner`
At the moment, there are quite a few tests missing for the `RangeCheckBuiltinRunner` structure in order to have good coverage. This generates problems in use as is the case here:

https://github.com/keep-starknet-strange/cairo-zig/blob/d043ccf85a54a5d566046fd86d0eafa65f762865/src/vm/builtins/builtin_runner/range_check.zig#L239

The test coverage needs to be improved for the whole structure.

### PR DESCRIPTION
**Pull request by oxlime**
should close #178 
unit tests 

added numBits() to field element

also should close #168 
just three lines so that it could handle negatives.

### CODE REVIEW

File: src/vm/builtins/builtin_runner/range_check.zig [hunk 1]
```diff
@@ -269,6 +276,32 @@ pub const RangeCheckBuiltinRunner = struct {
...
+///
+/// - `memory`: A `Memory` pointer of validation rules segment index.
+/// - `address`: A `Relocatable` pointer to the validation rule.
+///
+/// # Returns
+///
+/// An `ArrayList(Relocatable)` containing the rules address
+/// verification fails.
+pub fn rangeCheckValidationRule(memory: *Memory, address: Relocatable) MemoryError![]const Relocatable {
+    const num = ((memory.get(address) catch {
```
Comment (tcoratger) [inline src/vm/builtins/builtin_runner/range_check.zig:291]: We have a dedicated memory `getFelt` method specific for that no?

File: src/vm/builtins/builtin_runner/range_check.zig [hunk 2]
```diff
@@ -216,45 +217,51 @@ pub const RangeCheckBuiltinRunner = struct {
...
+    /// - `memory`: A `Memory` pointer.
     ///
-    /// # Modifies
+    /// # Returns
     ///
-    /// - `memory`: Adds validation rule to `memory`.
-    pub fn addValidationRule(self: *const Self, memory: *Memory) !void {
-        try memory.addValidationRule(@intCast(self.base), rangeCheckValidationRule);
+    /// - An `Array`containing the min and max of range check.
+    pub fn getRangeCheckUsage(self: *Self, memory: *Memory) ?[2]usize {
```
Comment (tcoratger) [inline src/vm/builtins/builtin_runner/range_check.zig:242]: I think that it is better to use a tuple here for the result, what do you think?

```zig
std.meta.Tuple(&.{ usize, usize })
```

You can find examples at other places of the code or here if needed: https://ziglang.org/documentation/master/#Tuples

File: src/vm/builtins/builtin_runner/range_check.zig [hunk 3]
```diff
@@ -296,3 +329,166 @@ test "used instances" {
...
+    const zero: usize = 0;
+    // assert
+    try std.testing.expectEqual(
+        res.?[1],
+        four,
+    );
+    try std.testing.expectEqual(
+        res.?[0],
+        zero,
+    );
```
Comment (tcoratger) [inline src/vm/builtins/builtin_runner/range_check.zig:359]: Here I know this is confusing in Zig but the expected value should come first. Also, if you use a tuple for the result of the function you could have a stronger test by doing:

```zig
try std.testing.expectEqual(
    @as(std.meta.Tuple(&.{ usize, usize }), .{ 0, 4 }),
    res.?
);
```
so as to test the complete result of the function in a single expect and thus be sure of the entirety of what we are testing.

If you ultimately choose to stay with an array, it is probably preferable to test the slice with the `expectEqualSlices` method in order to also be sure of the entire slice that you have as output.

File: src/vm/builtins/builtin_runner/range_check.zig [hunk 4]
```diff
@@ -296,3 +329,166 @@ test "used instances" {
...
+    const allocator = std.testing.allocator;
+    var mem = try MemorySegmentManager.init(allocator);
+    defer mem.deinit();
+
+    _ = builtin.getRangeCheckUsage(mem.memory);
+    // assert
+    try std.testing.expectEqual(
+        builtin.base,
+        0,
+    );
```
Comment (tcoratger) [inline src/vm/builtins/builtin_runner/range_check.zig:420]: Here should be the inverse like:

```zig
try std.testing.expectEqual(0, builtin.base);
```

File: src/vm/memory/memory.zig [hunk 5]
```diff
@@ -533,11 +533,12 @@ pub const Memory = struct {
...
-                    _ = list;
-                    // TODO: debug rangeCheckValidationRule to be able to push list here again
-                    try self.validated_addresses.addAddresses(&[_]Relocatable{address});
-                }
+                const list = try rule(self, address);
+                const firstElement = list[0];
+                // std.debug.print("list: {any}\n", .{list});
+                // Todo: this should works but not really neccessary
+                try self.validated_addresses.addAddresses(&[_]Relocatable{firstElement});
+                //try self.validated_addresses.addAddresses(&[_]Relocatable{address});
```
Comment (tcoratger) [inline src/vm/memory/memory.zig:541]: We can remove this debug line :)

**Review by tcoratger — APPROVED** [review]
