### PR TITLE
Fix `Segments` integration tests

### LINKED ISSUE #487: Fix `Segments` integration tests
Some bug spotted in `segments` hint - integrations test, find and fix problem.
All of them failed with `DiffAssertValues`.
```
cairo_programs/relocate_segments_with_offset.json
cairo_programs/relocate_segments.json
cairo_programs/relocate_temporary_segment_append.json
cairo_programs/relocate_temporary_segment_into_new.json
```

### PR DESCRIPTION
**Pull request by StringNick**
closes #487

### CODE REVIEW

File: src/hint_processor/segments.zig [hunk 1]
```diff
@@ -81,7 +82,7 @@ test "Segments: run relocate segments" {
     defer vm.deinit(); // Ensure cleanup.
 
     // Sets the frame pointer within the virtual machine to a specific relocatable value.
-    vm.run_context.*.fp.* = Relocatable.init(1, 2);
+    vm.run_context.fp.* = Relocatable.init(1, 2);
```
Comment (tcoratger) [inline src/hint_processor/segments.zig:85]: Can we merge #480 before?

This will become 

```zig
vm.run_context.fp.* = 2;
```

**Review by tcoratger — APPROVED** [review]
